# Basic Config
esphome:
  name: 1f-kitchen-esp-w-003
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: 1f-kitchen-esp-w-003.iot

#logger:
ota:
  platform: esphome

api:

switch:
  - platform: gpio
    name: "Sandwich"
    pin: GPIO4
    id: sandwich
    on_turn_on:
      - script.execute: sandwich_failsafe

script:
  - id: sandwich_failsafe
    mode:
      restart # Light will be kept on during 1 minute since
      # the latest time the script is executed
    then:
      - delay: 10 min
      - switch.turn_off: sandwich
