esphome:
  name: bedroom_helper
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom Helper Fallback Hotspot"
    password: "Z5PfiDs5Tzm5"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    pin: D1
    name: "Mood Lights"
    icon: "mdi:string-lights"
  - platform: gpio
    pin: D2
    inverted: yes
    id: projector_button
  - platform: template
    name: "Projector"
    icon: "mdi:projector"
    id: projector
    turn_on_action:
      then:
      - switch.turn_on: projector_button
      - delay: 0.5s
      - switch.turn_off: projector_button
      - switch.template.publish:
            id: projector
            state: ON
    turn_off_action:
      then:
      - switch.turn_on: projector_button
      - delay: 0.5s
      - switch.turn_off: projector_button
      - delay: 1s
      - switch.turn_on: projector_button
      - delay: 0.5s
      - switch.turn_off: projector_button
      - switch.template.publish:
            id: projector
            state: OFF