esphome:
  name: bus
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Sandwich Fallback Hotspot"
  #   password: "Z5PfiDs5Tzm5"

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D2
  scl: D1
  frequency: 800kHz


display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display

    #reset_pin: D0
    address: 0x3C
    pages:
      - id: page1
        lambda: |-
          it.strftime(5, 60, id(roboto), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());

          it.print(64,0, id(roboto_small),TextAlign::TOP_LEFT ,  "V3 C3D");
          it.print(64,16, id(roboto_small),TextAlign::TOP_LEFT , "V5 C3D");
          it.print(64,32, id(roboto_small),TextAlign::TOP_LEFT , "V5 C3U");
          it.print(64,48, id(roboto_small),TextAlign::TOP_LEFT , "V5 LCO");

          if (!std::isnan(id(v3_1378).state)) {
          it.printf(128,0, id(roboto_small),TextAlign::TOP_RIGHT ,  "%02.0f", id(v3_1378).state);
          }else{
          it.print(128,0, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (!std::isnan(id(v5_1378).state)) {
          it.printf(128,16, id(roboto_small),TextAlign::TOP_RIGHT , "%02.0f", id(v5_1378).state);
          }else{
          it.print(128,16, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (!std::isnan(id(v5_291).state)) {
          it.printf(128,32, id(roboto_small),TextAlign::TOP_RIGHT , "%02.0f", id(v5_291).state);
          }else{
          it.print(128,32, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (!std::isnan(id(v5_3524).state)) {
          it.printf(128,48, id(roboto_small),TextAlign::TOP_RIGHT , "%02.0f", id(v5_3524).state);
          }else{
          it.print(128,48, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (id(weather_state).has_state()) {
          std::map<std::string, std::string> weather_icon_map
            {
              {"clear-night", "\U000F0594"},
              {"cloudy", "\U000F0590"},
              {"fog", "\U000F0591"},
              {"hail", "\U000F0592"},
              {"lightning", "\U000F0593"},
              {"lightning-rainy", "\U000F067E"},
              {"partlycloudy", "\U000F0595"},
              {"pouring", "\U000F0596"},
              {"rainy", "\U000F0597"},
              {"snowy", "\U000F0598"},
              {"snowy-rainy", "\U000F067F"},
              {"sunny", "\U000F0599"},
              {"windy", "\U000F059D"},
              {"windy-variant", "\U000F059E"},
            };
          it.printf(10, 5, id(font4), TextAlign::TOP_LEFT, weather_icon_map[id(weather_state).state.c_str()].c_str());
          }

# interval:
#   - interval: 4s
#     then:
#       - display.page.show_next: my_display
#       - component.update: my_display

# https://community.home-assistant.io/t/esphome-ha-timer-helper-on-display/390235/9
# https://esphome.io/components/text_sensor/index.html
font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 14

  - file: 'config/materialdesignicons-webfont.ttf'
    id: font4
    size: 40
    glyphs:
      - "\U000F0594" #"clear-night"
      - "\U000F0590" #"cloudy"
      - "\U000F0591" #"fog"
      - "\U000F0592" #"hail"
      - "\U000F0593" #"lightning"
      - "\U000F067E" #"lightning-rainy"
      - "\U000F0595" #"partlycloudy"
      - "\U000F0596" #"pouring"
      - "\U000F0597" #"rainy"
      - "\U000F0598" #"snowy"
      - "\U000F067F" #"snowy-rainy"
      - "\U000F0599" #"sunny"
      - "\U000F059D" #"windy"
      - "\U000F059E" #"windy-variant"

time:
  - platform: sntp
    id: esptime

sensor:
  - platform: homeassistant
    id: v3_1378
    entity_id: sensor.v3_1378
  - platform: homeassistant
    id: v5_1378
    entity_id: sensor.v5_1378
  - platform: homeassistant
    id: v5_291
    entity_id: sensor.v5_291
  - platform: homeassistant
    id: v5_3524
    entity_id: sensor.v5_3524

text_sensor:
  - platform: homeassistant
    id: weather_state
    name: "Current Weather Icon"
    entity_id: weather.can_garri
    internal: true