esphome:
  name: esp-datacenter
  platform: ESP32
  board: esp32-c3-devkitm-1
  platformio_options:
    board_build.flash_mode: dio

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: esp-datacenter.iot

# Enable logging
# logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

mqtt:
  broker: mqtt.jserrats.xyz
  topic_prefix: esphome/datacenter
  on_json_message:
    topic: zigbee2mqtt/house_power_sensor
    then:
    - sensor.template.publish:
        id: house_power
        state: !lambda 'return x["power"];'

i2c:
  sda: GPIO04
  scl: GPIO05
  frequency: 400kHz

text_sensor:
  - platform: mqtt_subscribe
    id: sandwich_timer
    topic: automations/timer/sandwich/text_countdown

sensor:
  - platform: homeassistant
    id: ha_temperature
    entity_id: weather.can_garri
    attribute: temperature

  - platform: template
    id: house_power

  - platform: mqtt_subscribe
    id: pm2_5
    topic: esphome/airquality/sensor/pm_2_5/state

  - platform: mqtt_subscribe
    id: desk_height
    topic: esphome/standing-desk/sensor/desk_height/state

  - platform: scd4x
    co2:
      name: "CO2"
      id: CO2
    temperature:
      name: temperature
    humidity:
      name: humidity

  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: Studio Presence
      on_press:
        then:
          - lambda: |-
              id(mydisplay).backlight();
      on_release:
        then:
          - lambda: |-
              id(mydisplay).no_backlight();

uart:
  tx_pin: GPIO00
  rx_pin: GPIO01
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

number:
  - platform: ld2410
    timeout:
      name: Studio presence timeout
    max_move_distance_gate:
      name: Studio max move distance gate
    max_still_distance_gate:
      name: Studio max still distance gate
    g2:
      move_threshold:
        name: Studio g2 move threshold
      still_threshold:
        name: Studio g2 still threshold

switch:
  - platform: ld2410
    bluetooth:
      name: "Studio LD2410 Bluetooth"

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    id: mydisplay
    update_interval: 1s
    lambda: |-
      // Print the current time
      //it.strftime(6,0,"%X", id(esptime).now());
      //it.strftime(1,1,"%a %d/%m/%Y W%W", id(esptime).now());
      it.printf(0,2, "PM25:%2.0f", id(pm2_5).state);
      it.printf(0,1, "CO2 :%2.0f", id(CO2).state);
      it.printf(10,1, "DH:%2.1f", id(desk_height).state);
      it.printf(10,2, "BIK:%s", id(sandwich_timer).state.c_str());
      it.printf(0,3,"PWR:%2.0f%W ", id(house_power).state);
      it.printf(10,3,"TMP:%2.0fC ", id(ha_temperature).state);

output:
  - platform: ledc
    pin: GPIO03
    id: rtttl_out

rtttl:
  output: rtttl_out

button:
  - platform: template
    name: "Studio Audio notification"
    on_press:
      then:
        - rtttl.play: "siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e"
