esphome:
    name: esp-desk-screen
    platform: ESP8266
    board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: esp-desk-screen.iot
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "desk Fallback Hotspot"
  #   password: "Z5PfiDs5Tzm5"

# Enable logging
logger:

ota:
# Enable Home Assistant API
api:

i2c:
  sda: D1
  scl: D2
  frequency: 800kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display
    rotation: 180
    #reset_pin: D0
    address: 0x3C
    pages:
      - id: page1
        lambda: |-
          if(id(desk).state){
          std::map<std::string, std::string> weather_icon_map
            {
              {"clear-night", "\U000F0594"},
              {"cloudy", "\U000F0590"},
              {"fog", "\U000F0591"},
              {"hail", "\U000F0592"},
              {"lightning", "\U000F0593"},
              {"lightning-rainy", "\U000F067E"},
              {"partlycloudy", "\U000F0595"},
              {"pouring", "\U000F0596"},
              {"rainy", "\U000F0597"},
              {"snowy", "\U000F0598"},
              {"snowy-rainy", "\U000F067F"},
              {"sunny", "\U000F0599"},
              {"windy", "\U000F059D"},
              {"windy-variant", "\U000F059E"},
            };

          it.strftime(0, -4, id(jet), TextAlign::TOP_LEFT, "%H:%M", id(esptime).now());
          it.strftime(128, 0, id(jet_small), TextAlign::TOP_RIGHT, "%a %d", id(esptime).now());
          it.strftime(128, 23, id(jet_small), TextAlign::BASELINE_RIGHT, "%b %y", id(esptime).now());
          
          it.printf(64, 38,id(jet_small), TextAlign::BASELINE_CENTER, "%2.0f°C %2.0f%W", id(temperature).state, id(shelly1pm0_power).state);
          it.printf(0,40,id(icons), TextAlign::BASELINE_LEFT, weather_icon_map[id(weather_state).state.c_str()].c_str());

          it.printf(64,52, id(jet_very_small), TextAlign::BASELINE_CENTER, "%s", id(media_title).state.c_str());
          it.printf(64,64, id(jet_very_small), TextAlign::BASELINE_CENTER, "%s", id(media_artist).state.c_str());
          }

sensor:
  - platform: homeassistant
    #name: "Weather Forecast From Home Assistant"
    id: temperature
    entity_id: weather.can_garri
    attribute: temperature
  - platform: homeassistant
    name: "sensor.shelly1pm0_power"
    id: shelly1pm0_power
    entity_id: sensor.shelly1pm0_power
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

text_sensor:
  - platform: homeassistant
   # name: "media_title"
    id: media_title
    entity_id: media_player.spotify_jaume_serrats9
    attribute: media_title
  - platform: homeassistant
   # name: "media_artist"
    id: media_artist
    entity_id: media_player.spotify_jaume_serrats9
    attribute: media_artist
  - platform: homeassistant
    id: weather_state
    name: "Current Weather Icon"
    entity_id: weather.can_garri
    internal: true

binary_sensor:
  - platform: homeassistant
   # name: "desk"
    id: desk
    entity_id: switch.power1
  - platform: ld2410
    has_target:
      name: Presence
      on_state:
        then:
          - light.turn_on: 
              id: led
              red: 0%
              green: 100%
              blue: 70%
              flash_length: 1s
              #effect: addressable_scan
          - delay: 1s
          - light.turn_off: led
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

time:
- platform: sntp
  id: esptime

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: D8
    num_leds: 6
    id: led
    name: Desk notification light
    effects:
      - pulse:
      - addressable_color_wipe:
      - addressable_rainbow:
      - addressable_scan:

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  timeout: 5s
  max_move_distance : 6m
  max_still_distance: 4.5m
  # g5_still_threshold: 80
  # g6_still_threshold: 100
  # g7_still_threshold: 100
  # g8_still_threshold: 100


font:
  # gfonts://family[@weight]
  - file: "gfonts://Ubuntu Mono"
    id: jet
    size: 30
  - file: "gfonts://Ubuntu Mono"
    id: jet_small
    size: 15
  - file: "gfonts://Ubuntu Mono"
    id: jet_very_small
    size: 12

  #https://pictogrammers.github.io/@mdi/font/2.0.46/
  - file: 'config/materialdesignicons-webfont.ttf'
    id: icons
    size: 15
    glyphs:
      - "\U000F0483" #""
      - "\U000F0499" #""
      - "\U000F0594" #"clear-night"
      - "\U000F0590" #"cloudy"
      - "\U000F0591" #"fog"
      - "\U000F0592" #"hail"
      - "\U000F0593" #"lightning"
      - "\U000F067E" #"lightning-rainy"
      - "\U000F0595" #"partlycloudy"
      - "\U000F0596" #"pouring"
      - "\U000F0597" #"rainy"
      - "\U000F0598" #"snowy"
      - "\U000F067F" #"snowy-rainy"
      - "\U000F0599" #"sunny"
      - "\U000F059D" #"windy"
      - "\U000F059E" #"windy-variant"

