esphome:
  name: esp-kitchen
  platform: ESP32
  board: esp32-c3-devkitm-1
  platformio_options:
    board_build.flash_mode: dio

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: esp-kitchen.iot

# captive_portal:

# Enable logging
# logger:

# Enable Home Assistant API
# api:

mqtt:
  broker: mqtt.jserrats.xyz
  topic_prefix: esphome/kitchen
  discovery_prefix: homeassistant

ota:
  platform: esphome

time:
  - platform: sntp
    id: esptime

i2c:
  sda: GPIO04
  scl: GPIO05
  frequency: 400kHz

binary_sensor:
  - platform: gpio
    id: sandwitch_button
    pin:
      number: GPIO19
      mode: INPUT_PULLDOWN
    on_press:
      then:
        - mqtt.publish:
            topic: esphome/sandwich/switch/sandwich/command
            payload: "toggle"
        - rtttl.play: "Blue:d=4,o=5,b=140:a,a#,8g,8a#,8c6,8f,8a,a#"
    on_double_click:
      - rtttl.play: "Blue(Dab:d=4,o=5,b=140:8g,8a#,8d6,d#6,8d6,8c6,a#,8g,8a#,8c6,8f,8a,a#,8g,8a#,8d6,d#6,8d6,8c6,a#,8g,8a#,8c6,8f,8a,a#,8g,8a#,8d6,d#6,8d6,8c6,a#,8g,8a#,8a,8f,8f,2g"

  - platform: gpio
    id: sweep_button
    pin:
      number: GPIO18
    on_press:
      then:
        - rtttl.play: "siren:d=8,o=5,b=100:f"
        - mqtt.publish:
            topic: homeassistant/custom/clean/kitchen
            payload: ""

text_sensor:
  - platform: mqtt_subscribe
    id: sandwich_timer
    topic: automations/timer/sandwich/text_countdown

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    id: my_display_oled
    rotation: 180°
    address: 0x3C
    pages:
      - id: page1
        lambda: |-
          it.strftime(5, 60, id(roboto), TextAlign::BASELINE_LEFT, "%H:%M   %d/%m", id(esptime).now());
          it.printf(0,20, id(roboto),TextAlign::TOP_LEFT ,  "BIKINI: %s", id(sandwich_timer).state.c_str());

output:
  - platform: ledc #esp8266_pwm
    pin: GPIO03
    id: rtttl_out

rtttl:
  output: rtttl_out

button:
  - platform: template
    name: "Kitchen audio notification"
    on_press:
      then:
        - rtttl.play: "siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e"

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 14
