esphome:
  name: lcd
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LCD Fallback Hotspot"
    password: "Z5PfiDs5Tzm5"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: notify_lcd
      variables:
        message: string
      then:
        - lambda: |-
            id(mydisplay).printf(0,3, message);
ota:

i2c:
  sda: D2
  scl: D1

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    id: mydisplay
    lambda: |-
      // Print the current time
      it.strftime("%X %a %d %b", id(my_time).now());

      it.printf(0,1,"TMP:%2.1fC ", id(temperature).state);
      it.printf(11,1,"HUM:%2.1f%%", id(humidity).state);

      it.printf(0,2,"RAM:%2.1f%% ", id(glances_ram_used_percent).state);
      it.printf(11,2,"CPU:%2.1f%%", id(glances_cpu_used).state);

time:
- platform: sntp
  id: my_time

switch:
  - platform: template
    id: backlight
    name: LCD Backlight
    icon: mdi:brightness-6
    turn_on_action:
      then:
        - lambda: |-
            id(mydisplay).backlight();
        - switch.template.publish:
            id: backlight
            state: ON
    turn_off_action:
      then:
        - lambda: |-
            id(mydisplay).no_backlight();
        - switch.template.publish:
            id: backlight
            state: OFF

sensor:
  - platform: homeassistant
    name: "Weather Forecast From Home Assistant"
    id: temperature
    entity_id: weather.can_gaudir
    attribute: temperature
  - platform: homeassistant
    name: "Weather Forecast From Home Assistant"
    id: humidity
    entity_id: weather.can_gaudir
    attribute: humidity
  - platform: homeassistant
    name: "glances_ram_used_percent"
    id: glances_ram_used_percent
    entity_id: sensor.glances_ram_used_percent
  - platform: homeassistant
    name: "glances_cpu_used"
    id: glances_cpu_used
    entity_id: sensor.glances_cpu_used
text_sensor:
  - platform: homeassistant
    name: "Weather Forecast From Home Assistant"
    id: next_dawn
    entity_id: sun.sun
    attribute: next_dawn
  - platform: homeassistant
    name: "media_title"
    id: media_title
    entity_id: media_player.mpd
    attribute: media_title