esphome:
  name: esp-lobby
  platform: ESP32
  board: esp32-c3-devkitm-1
  platformio_options:
    board_build.flash_mode: dio

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: esp-lobby.iot

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: sntp
    id: esptime

i2c:
  sda: GPIO04
  scl: GPIO05
  frequency: 400kHz

binary_sensor:
  - platform: homeassistant
    id: deadbolt
    entity_id: binary_sensor.door_deadbolt
    on_press:
      then:
        - light.turn_on:
            id: led
            effect: "Scan"
            blue: 0%
            green: 0%
            red: 100%
    on_release:
      - light.turn_off: led

  - platform: gpio
    id: door
    name: "Main Door"
    pin:
      number: GPIO19
      mode: INPUT_PULLDOWN
    on_press:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: light.lobby_light
        - rtttl.play: "zelda_gerudo:d=4,o=5,b=125:16c#,16f#,16g#,8a,16p,16c#,16f#,16g#,a"

  - platform: ld2410
    has_target:
      name: Lobby Presence
      on_press:
        then:
          - homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.lobby_light
      on_release:
        then:
          - homeassistant.service:
              service: light.turn_off
              data:
                entity_id: light.lobby_light
switch:
  - platform: ld2410
    bluetooth:
      name: "Lobby LD2410 Bluetooth"

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO06
    num_leds: 8
    id: led
    effects:
      - pulse:
      - addressable_color_wipe:
      - addressable_rainbow:
      - addressable_scan:
          name: "Scan"
      - addressable_twinkle:
      - addressable_random_twinkle:

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    id: my_display_oled
    #reset_pin: D0
    address: 0x3C
    pages:
      - id: page1
        lambda: |-
          it.strftime(5, 60, id(roboto), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());

          it.print(64,0, id(roboto_small),TextAlign::TOP_LEFT ,  "V3 C3D");
          it.print(64,16, id(roboto_small),TextAlign::TOP_LEFT , "V5 C3D");
          it.print(64,32, id(roboto_small),TextAlign::TOP_LEFT , "V5 C3U");
          it.print(64,48, id(roboto_small),TextAlign::TOP_LEFT , "V5 LCO");

          if (!std::isnan(id(v3_1378).state)) {
          it.printf(128,0, id(roboto_small),TextAlign::TOP_RIGHT ,  "%02.0f", id(v3_1378).state);
          }else{
          it.print(128,0, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (!std::isnan(id(v5_1378).state)) {
          it.printf(128,16, id(roboto_small),TextAlign::TOP_RIGHT , "%02.0f", id(v5_1378).state);
          }else{
          it.print(128,16, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (!std::isnan(id(v5_291).state)) {
          it.printf(128,32, id(roboto_small),TextAlign::TOP_RIGHT , "%02.0f", id(v5_291).state);
          }else{
          it.print(128,32, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (!std::isnan(id(v5_3524).state)) {
          it.printf(128,48, id(roboto_small),TextAlign::TOP_RIGHT , "%02.0f", id(v5_3524).state);
          }else{
          it.print(128,48, id(roboto_small),TextAlign::TOP_RIGHT , "- ");
          }

          if (id(weather_state).has_state()) {
          std::map<std::string, std::string> weather_icon_map
            {
              {"clear-night", "\U000F0594"},
              {"cloudy", "\U000F0590"},
              {"fog", "\U000F0591"},
              {"hail", "\U000F0592"},
              {"lightning", "\U000F0593"},
              {"lightning-rainy", "\U000F067E"},
              {"partlycloudy", "\U000F0595"},
              {"pouring", "\U000F0596"},
              {"rainy", "\U000F0597"},
              {"snowy", "\U000F0598"},
              {"snowy-rainy", "\U000F067F"},
              {"sunny", "\U000F0599"},
              {"windy", "\U000F059D"},
              {"windy-variant", "\U000F059E"},
            };
          it.printf(10, 5, id(font4), TextAlign::TOP_LEFT, weather_icon_map[id(weather_state).state.c_str()].c_str());
          }
output:
  - platform: ledc #esp8266_pwm
    pin: GPIO03
    id: rtttl_out

rtttl:
  output: rtttl_out

button:
  - platform: template
    name: "Lobby audio notification"
    on_press:
      then:
        - rtttl.play: "siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e"

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 14

  - file: "config/materialdesignicons-webfont.ttf"
    id: font4
    size: 40
    glyphs:
      - "\U000F0594" #"clear-night"
      - "\U000F0590" #"cloudy"
      - "\U000F0591" #"fog"
      - "\U000F0592" #"hail"
      - "\U000F0593" #"lightning"
      - "\U000F067E" #"lightning-rainy"
      - "\U000F0595" #"partlycloudy"
      - "\U000F0596" #"pouring"
      - "\U000F0597" #"rainy"
      - "\U000F0598" #"snowy"
      - "\U000F067F" #"snowy-rainy"
      - "\U000F0599" #"sunny"
      - "\U000F059D" #"windy"
      - "\U000F059E" #"windy-variant"

sensor:
  - platform: homeassistant
    id: v3_1378
    entity_id: sensor.v3_1378
  - platform: homeassistant
    id: v5_1378
    entity_id: sensor.v5_1378
  - platform: homeassistant
    id: v5_291
    entity_id: sensor.v5_291
  - platform: homeassistant
    id: v5_3524
    entity_id: sensor.v5_3524

text_sensor:
  - platform: homeassistant
    id: weather_state
    name: "Current Weather Icon"
    entity_id: weather.can_garri
    internal: true

ld2410:

uart:
  tx_pin: GPIO00
  rx_pin: GPIO01
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

number:
  - platform: ld2410
    timeout:
      name: Lobby presence timeout
    max_move_distance_gate:
      name: Lobby max move distance gate
    max_still_distance_gate:
      name: Lobby max still distance gate
