esphome:
  name: minimatrix
  platform: ESP32
  board: nodemcu-32s

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_pass

# ota:

# Enable logging
logger:

# Enable Home Assistant API
#api:


# display:
#   - platform: addressable_light
#     id: led_matrix_display
#     addressable_light_id: led_matrix_light
#     width: 8
#     height: 8
#     update_interval: 16ms
#     lambda: |-
#           // Draw a bulls-eye pattern
#           Color red = Color(0xFF0000);
#           Color green = Color(0x00FF00);
#           Color blue = Color(0x0000FF);
#           it.rectangle(0, 0, 8, 8, red);
#           it.rectangle(1, 1, 6, 6, green);
#           it.rectangle(2, 2, 4, 4, blue);
#           it.rectangle(3, 3, 2, 2, red);

# light:
#   - platform: neopixelbus
#     type: GRB
#     variant: WS2811
#     pin: GPIO5
#     num_leds: 64
#     name: "NeoPixel Light"
#     id: led_matrix_light
    #default_transition_length: 0s
    # method:
    #   type: esp32_i2s
    # effects:
    #   - pulse:
    #       name: "Fast Pulse"
    #       transition_length: 0.5s
    #       update_interval: 0.5s

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO5
    num_leds: 64
    type: GRB
    name: "led_matrix"
    id: led_matrix_light
    default_transition_length: 0s
    color_correct: [50%, 50%, 50%]
    restore_mode: ALWAYS_ON
    method:
      type: bit_bang
display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: led_matrix_light
    width: 8
    height: 8
    rotation: 180°
    update_interval: 16ms
    lambda: |-
          // Draw a bulls-eye pattern
          Color red = Color(0xFF0000);
          Color green = Color(0x00FF00);
          Color blue = Color(0x0000FF);
          it.rectangle(0, 0, 8, 8, red);
          it.rectangle(1, 1, 6, 6, green);
          it.rectangle(2, 2, 4, 4, blue);
          it.rectangle(3, 3, 2, 2, red);
          //it.line(0,0,32,0)