# Basic Config
esphome:
  name: esp-sandwich
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: esp-sandwich.iot

mqtt:
  broker: mqtt.jserrats.xyz
  topic_prefix: esphome/sandwich
  discovery_prefix: homeassistant

#logger:
ota:

switch:
  - platform: gpio
    name: "Sandwich"
    pin: GPIO4
    id: sandwich
    on_turn_on:
      - script.execute: sandwich_failsafe

script:
  - id: sandwich_failsafe
    mode:
      restart # Light will be kept on during 1 minute since
      # the latest time the script is executed
    then:
      - delay: 10 min
      - switch.turn_off: sandwich
