esphome:
  name: sgmk2-cam
  platform: ESP32
  board: esp32dev
  # on_boot:
  #   then:
  #     - light.turn_on: cam_light
  #     - delay: 0.2s
  #     - light.turn_off: cam_light
      
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: True
  use_address: sgmk2-cam.iot

#logger:

ota:
  platform: esphome

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: Cam
  vertical_flip: false
  horizontal_mirror: false

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    id: cam_light

esp32_camera_web_server:
  - port: 8080
    mode: stream

mqtt:
  broker: mqtt.jserrats.xyz
  discovery: false