esphome:
  name: esp-switches4
  platform: ESP8266
  board: nodemcuv2

wifi:
  use_address: esp-switches4.iot
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Switches4 Fallback Hotspot"
    password: "Z5PfiDs5Tzm5"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:

  - platform: gpio
    id: studio_fan_power
    pin:
      number: D1
      inverted: True
      mode: INPUT_PULLUP
      id: workbench_power
    filters:
    - delayed_on_off: 50ms
    on_press:
      then:
        - homeassistant.service:
            service: fan.turn_on
            data:
              entity_id: fan.power7
    on_release:
      then:
        - homeassistant.service:
            service: fan.turn_off
            data:
              entity_id: fan.power7


  - platform: gpio
    pin: 
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    id: printer
    filters: 
    - delayed_on_off: 50ms
    on_press:
      then:
        - homeassistant.service:
            service: switch.turn_on
            data:
              entity_id: switch.power5
    on_release:
      then:
        - homeassistant.service:
            service: switch.turn_off
            data:
              entity_id: switch.power5

  - platform: gpio
    pin: 
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    id: wled_rack
    filters: 
    - delayed_on_off: 50ms
    on_press:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: light.rack
    on_release:
      then:
        - homeassistant.service:
            service: light.turn_off
            data:
              entity_id: light.rack

  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    id: desk
    filters: 
    - delayed_on_off: 50ms
    on_press:
      then:
        - homeassistant.service:
            service: switch.turn_on
            data:
              entity_id: switch.desk
    on_release:
      then:
        - homeassistant.service:
            service: switch.turn_off
            data:
              entity_id: switch.desk