substitutions:
  name: esp-zigbee
  device_description: "ZB-GW03 eWeLink Ethernet Zigbee Gateway based Zigbee Coordinator"

ethernet:
  use_address: esp-zigbee.iot

logger:
  level: ERROR
  
mqtt:
  broker: mqtt.jserrats.xyz
  topic_prefix: esphome/zigbee

packages:
  zb-gw03:
    url: https://github.com/jserrats/esphome-zb-gw03
    ref: main
    files:
      - packages/core.yaml
      - packages/ethernet.yaml
      - packages/status_led.yaml
      - packages/green_led.yaml
      - packages/i2c.yaml
      - packages/button_zigbee_reset.yaml
      #- packages/mdns.yaml
    refresh: 0s
