esphome:
  name: esp-datacenter
  platform: ESP32
  board: wt32-eth01
  platformio_options:
    board_build.flash_mode: dio

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16
  use_address: esp-eth-test.iot